config/routes.rb
Sklep::Application.routes.draw do
  
  namespace :admin do
    root :to => "order#index"
    resources :order, :only => [:index, :show]
    resources :product
    resources :category
    
    devise_for :admin_users
  end

  root :to => "shop#index"
  
  resources :product, :only => [:index, :show, :update, :destroy]
  resources :category, :only => [:show]
  resources :cart, :only => [:index, :new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  has_many :orders

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderitems
  attr_accessible :confirmed

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  attr_accessible :order_id, :product_id, :quantity
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price, :category_id
  belongs_to :category
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_admin_admin_user!
end

app/controllers/admin/category_controller.rb
#!/bin/env ruby
# encoding: utf-8
class Admin::CategoryController < Admin::AdminController
  def index
    @categories = Category.all
  end
  
  def new
    @cat = Category.new
    
  end
  
  def create
    if Category.create(params[:category])
      redirect_to admin_category_index_path, :notice => "Dodano kategorię"  
    else
      redirect_to admin_category_index_path, :alert => "Nie udało się dodać kategorii"
    end    
  end
    
  def show
    @category = Category.find(params[:id])
  end
  
  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_category_index_path, :notice => "Usunięto kategorię"
  end
  
  def update
    if Category.find(params[:id]).update_attributes(params[:category])
      redirect_to admin_category_index_path, :notice => "Zmieniono nazwę kategorii"
    else
      redirect_to admin_category_index_path, :notice => "Nie zmieniono nazwy kategorii"
    end
    
  end
  
end

app/controllers/admin/order_controller.rb
class Admin::OrderController < Admin::AdminController
  
  def index
     @orders = Order.where(:confirmed => true).all
  end
  
  def show
     @order = Order.find(params[:id])
     @items = @order.orderitems.all 
  end
  
end

app/controllers/admin/product_controller.rb
#!/bin/env ruby
# encoding: utf-8
class Admin::ProductController < Admin::AdminController
  def index
    @products = Product.all
  end
  
  def new
    @prod = Product.new
    @categories = Category.all.map {|x| [x.name, x.id]}

  end
  
  def create
    if Product.create(params[:product])
      redirect_to admin_product_index_path, :notice => "Dodano produkt"  
    else
      redirect_to admin_product_index_path, :alert => "Nie udało się dodać produktu"
    end    
  end
    
  def show
    @product = Product.find(params[:id])
    @categories = Category.all.map {|x| [x.name, x.id]}
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to admin_product_index_path, :notice => "Usunięto produkt"
  end
  
  def update
    if Product.find(params[:id]).update_attributes(params[:product])
      redirect_to admin_product_index_path, :notice => "Zmieniono produkt"
    else
      redirect_to admin_product_index_path, :notice => "Nie udało się zmienić produktu"
    end
    
  end
  
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  helper_method :shopping_cart, :current_buyer
  
  def current_buyer
    if cookies[:buyer_id] == nil or not Buyer.where(:id => cookies[:buyer_id]).exists
      cookies[:buyer_id] = Buyer.create.id
    end
    return Buyer.find(cookies[:buyer_id])
  end
  
  def shopping_cart
    current_buyer.orders.where(:confirmed => false).first || current_buyer.orders.create(:confirmed => false)
  end
  
  
  
end

app/controllers/cart_controller.rb
#!/bin/env ruby
# encoding: utf-8
class CartController < ApplicationController
  def index
    @items = shopping_cart.orderitems.all.sort
  end
  
  def new
    @items = shopping_cart.orderitems.all
  end
  
  def create
    cart = shopping_cart
    cart.full_address = params[:full_address]
    cart.confirmed = true
    if cart.save
      redirect_to :root, :notice => "Udało się przyjąć zamówienie!"
    else
      redirect_to :root, :alert => "Niestety, nie udało się przyjąć zamówienia"
    end
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  
  def show
    @c = Category.find(params["id"])
    @p = @c.products
  end
end

app/controllers/product_controller.rb
#!/bin/env ruby
# encoding: utf-8

class ProductController < ApplicationController
  
  def index
    @q = Product.search(params[:q])
    @results = @q.result(:distinct => true)
  end
  
  def show
    @p = Product.find(params["id"])
    order_item = shopping_cart.orderitems.where(:product_id => params["id"])
    if order_item.length == 0
      @quantity = 0
    else
      order_item = order_item.first
      @quantity = order_item.quantity
    end
    
  end
  
  def change_quantity_in_cart x, komunikat
    order_item = Orderitem.where(:order_id => shopping_cart.id, :product_id => params["id"])
    if order_item.length == 0
      order_item = Orderitem.new(:order_id => shopping_cart.id, :product_id => params["id"])
      order_item.quantity = x;
    else
      order_item = order_item.first
      order_item.quantity += x
    end
    
    if order_item.quantity < 1
      order_item.destroy
      redirect_to :back, :notice => komunikat
    elsif order_item.save 
      redirect_to :back, :notice => komunikat
    else
      redirect_to :back, :alert => "Nie udało się zapisać zmian!"
    end
  end
  
  def update
    change_quantity_in_cart 1, "Dodano produkt do koszyka"
  end
  
  
  def destroy
    change_quantity_in_cart -1, "Usunięto jedną sztukę z koszyka"
  end
  
end

app/controllers/shop_controller.rb
#!/bin/env ruby
# encoding: utf-8

class ShopController < ApplicationController
  
  def index
    @prod = Product.order(:created_at).limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_admin_sidebar.html.erb
<div>
<h2>Zamówienia</h2>
<%= link_to "Przeglądaj", admin_order_index_path %>	
</div>


<div>
<h2>Kategorie</h2>
<%= link_to "Przeglądaj", admin_category_index_path %><br>
<%= link_to "Dodaj", new_admin_category_path %>
</div>


<div>
<h2>Produkty</h2>
<%= link_to "Przeglądaj", admin_product_index_path %><br>
<%= link_to "Dodaj", new_admin_product_path %>
</div>

app/views/admin/category/index.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Kategorie produktów:</h3>

<table style="border-collapse: collapse;">
	<tr>
		<td width="50px">Id</td>
		<td width="200px">Nazwa</td>
		<td width="150px">Produkty</td>
		<td width="100px">Szczegóły</td>
	</tr>
	
<% @categories.each do |cat| %>
<tr style="border-top:1px dashed black;">
	<td><%= cat.id %></td>
	<td><%= cat.name %></td>
	<td><%= Product.where(:category_id => cat.id).count %></td>
	<td><%= link_to "szczegóły", admin_category_path(cat) %></td>
</tr>
<% end %>
</table>

app/views/admin/category/new.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Dodaj kategorię:</h3>
<%= form_for [:admin, @cat], :url => "/admin/category" do |f| %>
<%= f.text_field :name %>
<%= submit_tag("Dodaj kategorię") %>
<% end %>

app/views/admin/category/show.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Kategoria: <%= @category.name %></h3>

<div>
	<h4>Zmień nazwę:</h4>
	<%= form_for [:admin, @category] do |f| %>
	<%= f.text_field :name %>
	<%= submit_tag("Zmień nazwę") %>
	<% end %>
	
</div>

<div>
	<h4>Usuń kategorię:</h4>
	<%= form_for [:admin, @category], :method => :delete do %>
	<%= submit_tag("Usuń") %>
	<% end %>
</div>

app/views/admin/order/index.html.erb
<% content_for :sidebar do %>
<% render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Przeglądanie zamówień</h3>

<table style="border-collapse: collapse;"
<tr>
	<td width="280px">Data</td>
	<td width="250px">Adres</td>
	<td>Zobacz</td>
</tr>
<% @orders.each do |order| %>
<tr style="border-top:1px dashed black;">
	<td><%= order.updated_at %></td>
	<td><%= order.full_address %></td>
	<td><%= link_to "szczegóły", admin_order_path(order) %>
</tr>
<% end %>
</table>

app/views/admin/order/show.html.erb
<% content_for :sidebar do %>
<% render :partial => "admin/admin_sidebar" %>
<% end %>

<table style="border-collapse: collapse;">
<tr>
<td width="200px">Produkt</td>
<td width="100px">Cena</td>
<td width="100px">Ilość</td>
<td width="100px">Koszt</td>
<td></td>
</tr>

<% price = 0 %>
<% @items.each do |p| %>
	<% product = Product.find(p.product_id) %>
	<% price += product.price * p.quantity %>
	<tr style="border-top: 1px dashed black; ">
		<td><%= product.name %></td>
		<td><%= product.price %>zł</td>
		<td><%= p.quantity %></td>
		<td><%= (p.quantity * product.price).round(2) %> zł</td>
	</tr>

<% end %>
<tr>
	<td colspan=4 style="text-align: center;"><b>Razem: <%= price.round(2)%> zł</b></td>
</tr>
</table>
<div>
<h4>Data i godzina złożenia zamówienia:</h4>
<%= @order.updated_at %>
<h4>Pełny adres:</h4>
<pre><%= @order.full_address %></pre>	
</div>

app/views/admin/product/index.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Przedmioty:</h3>

<table style="border-collapse: collapse;">
	<tr>
		<td width="50px">Id</td>
		<td width="250px">Nazwa</td>
		<td width="150px">Kategoria</td>
		<td width="150px">Cena</td>
		<td width="100px">Szczegóły</td>
	</tr>
	
<% @products.each do |prod| %>
<tr style="border-top:1px dashed black;">
	<td><%= prod.id %></td>
	<td><%= prod.name %></td>
	<td><%= prod.category.name %></td>
	<td><%= prod.price %></td>
	<td><%= link_to "szczegóły", admin_product_path(prod) %></td>
</tr>
<% end %>
</table>

app/views/admin/product/new.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Dodaj produkt:</h3>
<%= form_for [:admin, @prod], :url => "/admin/product" do |f| %>
<%= label_tag :category_id, "Kategoria:" %>
<%= f.select(:category_id, options_for_select(@categories)) %><br>
<%= label_tag :name, "Nazwa:" %>
<%= f.text_field :name %><br>
<%= label_tag :description, "Opis:" %>
<%= f.text_area :description %><br>
<%= label_tag :price, "Cena:" %>
<%= f.text_field :price %><br>
<%= submit_tag("Dodaj nowy produkt") %>
<% end %>
	

app/views/admin/product/show.html.erb
<% content_for :sidebar do %>
<%= render :partial => "admin/admin_sidebar" %>
<% end %>

<h3>Produkt: <%= @product.name %></h3>

<div>
	<h4>Edytuj: </h4>
	<%= form_for [:admin, @product] do |f| %>
	<%= label_tag :category_id, "Kategoria:" %>
	<%= f.select(:category_id, options_for_select(@categories, @product.category_id)) %><br>
	<%= label_tag :name, "Nazwa:" %>
	<%= f.text_field :name %><br>
	<%= label_tag :description, "Opis:" %>
	<%= f.text_area :description %><br>
	<%= label_tag :price, "Cena:" %>
	<%= f.text_field :price %><br>
	<%= submit_tag("Zapisz zmiany w bazie danych") %>
	<% end %>
	
</div>

<div>
	<h4>Usuń produkt:</h4>
	<%= form_for [:admin, @product], :method => :delete do %>
	<%= submit_tag("Usuń") %>
	<% end %>
</div>

app/views/application/_cart_sidebar.html.erb
<div id="cart">
<h2>Mój koszyk</h2>

<ul style="padding-left:15px;">
<% shopping_cart.orderitems.each do |p| %>
<li>
<%= Product.find(p.product_id).name %>
<%= if p.quantity > 1 then "- #{p.quantity} razy" end %>
</li>
<% end %>
</ul>

<% if shopping_cart.orderitems.all.count == 0 %>
koszyk jest pusty
<% else %>
<%= link_to "Szczegóły i zamówienie", cart_index_path %>
<% end %>

</div>

app/views/application/_categories_sidebar.html.erb
<div id="categories">
<h2>Kategorie produktów</h2>
<% Category.all.each do |c| %>
<%= if category_path(c) == request.fullpath then c.name else link_to c.name, c end %>
<% end %>
</div>

app/views/cart/index.html.erb
<% content_for :sidebar do %>
<div><h2>Wyszukiwarka</h2>
<%= link_to "Znajdź produkt", product_index_path %>
</div>
<%= render partial: "application/categories_sidebar" %>
<% end %>

<h3>Zawartość Twojego koszyka:</h3>

<table style="border-collapse: collapse;">
<tr>
<td width="300px">Produkt</td>
<td width="150px">Ilość</td>
<td width="150px">Koszt</td>
<td></td>
</tr>

<% price = 0 %>
<% @items.each do |p| %>

	<% product = Product.find(p.product_id) %>
	<% price += product.price * p.quantity %>
	<tr style="border-top: 1px dashed black; margin-top: 10px;">
		<td><%= link_to product.name, product %></td>
		<td><%= p.quantity %></td>
		<td><%= (p.quantity * product.price).round(2) %> zł</td>
		<td>
			<%= form_for product, :method => :delete do %>
			<%= submit_tag("Usuń jeden") %>
			<% end %>
			<%= form_for product do %>
			<%= submit_tag("Dodaj jeden") %>
			<% end %>
		</td>
	</tr>

<% end %>
<tr>
	<td></td>
	<td></td>
	<td><u><b>Razem: </b><%= price.round(2) %></u></td>
	<td></td>
</tr>
</table>
<br><br>

<div style="width: inherit; text-align: center; margin-bottom: 30px;">
<%= link_to "Przechodzę do zamówienia", new_cart_path %>

app/views/cart/new.html.erb
<% content_for :sidebar do %>
&nbsp;
<%end%>

<table style="border-collapse: collapse;">
<tr>
<td width="200px">Produkt</td>
<td width="100px">Cena</td>
<td width="100px">Ilość</td>
<td width="100px">Koszt</td>
<td></td>
</tr>

<% price = 0 %>
<% @items.each do |p| %>
	<% product = Product.find(p.product_id) %>
	<% price += product.price * p.quantity %>
	<tr style="border-top: 1px dashed black; ">
		<td><%= product.name %></td>
		<td><%= product.price %>zł</td>
		<td><%= p.quantity %></td>
		<td><%= (p.quantity * product.price).round(2) %> zł</td>
	</tr>

<% end %>
<tr>
	<td colspan=4 style="text-align: center;"><b>Razem: <%= price.round(2)%> zł</b></td>
</tr>
</table>
<BR><BR>
	
<%= form_tag :action => "create" do %>
  <%= label_tag(:full_address, "Pełny adres wysyłki:") %>
  <%= text_area_tag(:full_address) %>
  <%= submit_tag("Zamawiam") %>
<% end %>

app/views/category/show.html.erb
<% content_for :sidebar do %>
<div><h2>Wyszukiwarka</h2>
<%= link_to "Znajdź produkt", product_index_path %>
</div>
<%= render partial: "application/categories_sidebar" %>
<%= render partial: "application/cart_sidebar" %>
<% end %>

<h3>Kategoria <%= @c.name %></h3>

<% if @p.length == 0 %>
	<p>Brak przedmiotów w tej kategorii</p>
<% else %>
	<ul>Przedmioty w tej kategorii:
	<% @p.each do |p| %>
		<li><%= link_to p.name, p %></li>
	<% end %>
	</ul>
<% end %>
<%= link_to "<Wróć", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sklep</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main">
<%= link_to content_tag("div", "", :id => "logo"), root_path %>
<div id="container">
<% if flash[:notice].to_s.length > 0 %>
<div id="notice">
	<div>
		<%= flash[:notice] %>
	</div>
</div>
<% end %>
<% if flash[:alert].to_s.length > 0 %>
<div id="alert">
	<div>
		<%= flash[:alert] %>
	</div>
</div>
<% end %>
<% if flash[:error].to_s.length > 0 %>
<div id="alert">
	<div>
		<%= flash[:error] %>
	</div>
</div>
<% end %>
<div id="leftbar">
<%= yield :sidebar %>
</div>
<div id="content">
<%= yield %>
</div>
</div>
</div>


</body>
</html>

app/views/product/index.html.erb
<% content_for :sidebar do %>

<%= render partial: "application/categories_sidebar" %>
<%= render partial: "application/cart_sidebar" %>
<% end %>


<%= search_form_for @q, :url => "/product" do |f| %>
  <%= f.label :name_cont, "Nazwa zawiera:" %>
  <%= f.text_field :name_cont %><br>
  <%= f.label :description_cont, "Opis zawiera:" %>
  <%= f.text_field :description_cont %><br>
  <%= f.label :price_gteq, "Cena od " %>
  <%= f.text_field :price_gteq %>
  <%= f.label :price_lteq, " do " %>
  <%= f.text_field :price_lteq %>
  
  <%= f.submit %>
<% end %>

<% @results.each do |p| %>
<div class="product">
<h3><%= p.name %></h3>
<div style="float: left">Cena: <i><%= p.price %> PLN</i></div>
<div style="float: right;"><%= link_to "Więcej >", p %></div>
<div style="clear:both;"></div>
</div>
<% end %> 
  

app/views/product/show.html.erb
<% content_for :sidebar do %>
<div><h2>Wyszukiwarka</h2>
<%= link_to "Znajdź produkt", product_index_path %>
</div>
<%= render partial: "application/categories_sidebar" %>
<%= render partial: "application/cart_sidebar" %>
<% end %>

<h3><%= @p.name %></h3>
<p>Kategoria <%= link_to @p.category.name, @p.category %></p>
<p><%= @p.description%></p>
<p>Cena: <i><%= @p.price %> PLN</i></p>

<% if @quantity > 0 %>
<p>W koszyku: <%= @quantity %> (<%= link_to "Szczegóły i zamówienie", cart_index_path %>)</p>
<%= form_for @p do %>
<%= submit_tag("Dodaj jeden") %>
<% end %>
<%= form_for @p, :method => :delete do %>
<%= submit_tag("Usuń jeden") %>
<% end %>
<% else %>
<%= form_for @p do %>
<%= submit_tag("Dodaj do koszyka") %>
<% end %>
<% end %>
<br>

<%= link_to "<Wróć", root_path %>

app/views/shop/index.html.erb
<% content_for :sidebar do %>
<div><h2>Wyszukiwarka</h2>
<%= link_to "Znajdź produkt", product_index_path %>
</div>
<%= render partial: "application/categories_sidebar" %>
<%= render partial: "application/cart_sidebar" %>
<% end %>


<p>Dzień dobry! Sklep zaprasza!</p>
<p>Najnowsze produkty:</p>
<% @prod.each do |p| %>
<div class="product">
<h3><%= p.name %></h3>
<div style="float: left">Cena: <i><%= p.price %> PLN</i></div>
<div style="float: right;"><%= link_to "Więcej >", p %></div>
<div style="clear:both;"></div>
</div>
<% end %> 
  